# These are supported funding model platforms

patreon: Cactochan
patreon: axorax
Eth: 0x9CE5E2179A95Ba94f1B723FbfAd4710a9891c9e3
BNB: 0x9CE5E2179A95Ba94f1B723FbfAd4710a9891c9e3
Monero: 41sDuZBpbgMBP8Dh7x6S1n7f5zphjjgd7baXC8FDkwH1cSUkHRU9WFUb7Ckr26rRQkgDGUDH1X4h7UGkG1xt6CmJ4kWtD9J
Duino Coin: darkmash
